### ISSUE TITLE
ImportError occur

### ISSUE THREAD

**Issue by Xiong5Heng** [pantor/frankx#13]
Thanks for you brilliant job!
I have successfully installed all the libraries according to the file ci.yml.
But I get following error when i import frankx:
from frankx import Affine, LinearRelativeMotion, Robot
error:
ImportError: libfrankx.so: cannot open shared object file: No such file or directory

Can you give some suggestions for fixing this?

**Comment by pantor** [comment]
With the newest version 0.1.1, this should be fixed.
