### ISSUE TITLE
libfranka aborted due to discontinuities

### ISSUE THREAD

**Issue by mwulmer** [pantor/frankx#14]
Hey everyone,

I was trying to run the examples that use the cartesian motion generator (e.g. linear.py, path.py) and I get exceptions thrown by libfranka. I am currently using the default frankx installation without Reflexxes. The errors that I get are mostly related to the jerk (cartesian_motion_generator_joint_acceleration_discontinuity) and acceleration (cartesian_motion_generator_joint_velocity_discontinuity). I assumed, since you can set them to a percentage of the maximum, that the limits can't be violated. Do you tune your constraints in a specific way or do you have another solution for that? 

Best regards
Max

**Comment by rubenjuerges** [comment]
@mwulmer Did you find a solution to these issues? We are struggling with similar problems when using the python async_target example. For us, specifying robot.set_dynamic_rel(0.3) and adding waypoints abruptly causes this exact effect.

**Comment by whyy812** [comment]
We are struggling with the similar issues,too. Could you please share the solutions if you have already solved the similar issues?

**Comment by mwulmer** [comment]
Hi, I did not manage to solve the problem with the position controlled motions. I think that the Panda robots work well when torque controlled but are brittle when controlling them through another interface.
