### ISSUE TITLE
Required version of Eigen

### ISSUE THREAD

**Issue by xEnVrE** [pantor/frankx#2]
I noticed that in

https://github.com/pantor/frankx/blob/6953ca9628a5ee86387bfe1804121ab5a5c3b2e5/CMakeLists.txt#L17

you are requesting a specific version of `Eigen`.

Is there any specific reason behind this choice? Is it possible to use other versions of the library?

Thank you.

**Comment by pantor** [comment]
To my knowledge, there were some changes in the EulerAngles module of Eigen between 3.3.6 -> 3.3.7. But I've removed the `exact` statement for future versions of Eigen (3.3.7 is the latest stable version).
