### ISSUE TITLE
Confusion with degree of freedoms

### ISSUE THREAD

**Issue by peetCreative** [pantor/frankx#29]
Hey Pantor,

Same as I mentioned in the elbow issue I opened recently for libfranka [here](https://github.com/frankaemika/libfranka/issues/109), I probably missout a concept for robotics in general or some specifics of Franka Emika.
However I specially had a hard time grabbing the term Degree of Freedom you use in ruckig and frankx. 
As the [const definition of degree of freedom](https://github.com/pantor/frankx/blob/6b568470f8e842e5fdf41fe1e54f9f8e092e8690/include/frankx/robot.hpp#L58) it must either reference to jointspace (7 joints) or cartesian space (x,y,z, pitch, yaw roll + elbow value). In setting up the motion generators you just use it for both. Maybe even though degree of freedom for cartesian space is same it would be nice if it's stored in separate const values. And add some explenations as a comment.
I'm also not right sure why elbow besides other joints can be seen as extra DOF? 

Best regards,
Peter

**Comment by peetCreative** [comment]
OK, like sometimes you start thinking about it... I start to grab the overall idea.  DOF in Jointspace equals  DOF in Cartesian Space +  Overhanging joints (like the elbow).

**Comment by pantor** [comment]
Hey @peetCreative, just a quick heads up that I've also seen #27 and #26 (and of course your email), and I will get back to you shortly. 

Yes, you're right that the DoFs in joint space is equal to the DoFs in Cartesian space + the so-called null space of the robot. As we want to control the entire configuration of the robot regardless of the underlying space, the DoFs is always 7 for the Franka.
