### ISSUE TITLE
How are you handling orientation singularity?

### ISSUE THREAD

**Issue by amichlee** [pantor/frankx#3]
It looks like you are using euler angles for orientation interpolation with reflexxes (though feel free to correct me if I am wrong!). How are you dealing with instability close to singularity?

**Comment by pantor** [comment]
That's a very good question!

Currently we don't deal with singularities, as we only perform very simple robot motions. In the long-term, the common solution with Reflexxes is to keep using Euler angles but transform them internally in way that no singularity occurs on the path between start and end angles. While this is of course just an approximation, it should work fine for real-world cases with Reflexxes.

Btw, feel free to create a pull request if you have hacked a solution yourself!

**Comment by amichlee** [comment]
Thanks! I will share some code/thoughts when I can.
