### ISSUE TITLE
Request updated builds for frankx on pypi

### ISSUE THREAD

**Issue by gautams3** [pantor/frankx#35]
It would be great to get the latest `frankx` when running `pip install frankx`
This, I believe, is a [manual process](https://widdowquinn.github.io/coding/update-pypi-package/), so a PR won't help.

Is there an active maintainer for this package who would be able to do this?
Another option is to have an automated process such as [this workflow](https://github.com/rlworkgroup/garage/blob/master/.github/workflows/ci.yml#L442) shared by @krzentner.

**Comment by pantor** [comment]
I've just released frankx 0.2.0 on PyPI. Thanks!
