### ISSUE TITLE
Update to libfranka 0.9.0

### ISSUE THREAD

**Issue by angelotavares** [pantor/frankx#36]
Hy, i'm working with a emika panda robot and the it requires the 0.9.0 version of libfrank. I would like to use frankx, do you have prediction for when libfranka version 0.9.0 will be supported?

**Comment by angelotavares** [comment]
Hi, i solve my problem by manually compiling and installing the necessary tools. In the build, it automatically catches the libfranca version 0.9.0. Is this the best way to go about my problem?

**Comment by pantor** [comment]
I've just release frankx 0.2.0 with the default libfranka version 0.9.0. Otherwise yes, manually installing frankx allows to change the libfranka version more flexibly.
