### ISSUE TITLE
Reading force value 

### ISSUE THREAD

**Issue by angelotavares** [pantor/frankx#37]
Hi @pantor , when i run the example file force_control.py it works perfectly, and it's visible where the force in Z in been measured:

  `linear_motion_data = MotionData().with_reaction(Reaction(Measure.ForceZ < -8.0, StopMotion()))  # [N]`

However when I try to see the value in the Measure.ForceZ it only returns `<_frankx.Measure object at 0x7f47cbcb6ab0>`, im I missing some definition in order to be able to get the force value? This is extremely important for my application. 

Thanks.

**Comment by MiguelASTavares** [comment]
I found a way to access these values by editing the python.cpp file. I have also made a PR using my organization account.
