### ISSUE TITLE
Is there any requirement or environment which could be installed well by pypi

### ISSUE THREAD

**Issue by syh4661** [pantor/frankx#4]
i want to install this package in pypi release but it can't be installed because of error

>>frankx-0.0.1-cp36-cp36m-manylinux2010_x86_64.whl is not a supported wheel on this platform

I think this come out because of dismatching environment. But the python version is 3.6.10

is there any environment we have to fit?

or

is there any guide for install this package without pypi packaging whl file?

**Comment by pantor** [comment]
Frankx is deployed on PyPI only for Linux and Python 3.5, 3.6 and 3.7.
