### ISSUE TITLE
ValueError: libfranka: Attempt to set invalid transformation in motion generator. Has to be column major!

### ISSUE THREAD

**Issue by nily-dti** [pantor/frankx#7]
Hi @pantor 

I know this is a libfranka issue, but maybe you can help fix it. When I run `example/home.py` i get:

```
# python3 examples/home.py 
initial position:   0.529378
  0.123311
   0.37398
   2.35987
-0.0296578
 0.0611505
 -0.643318
initial velocity: 0
0
0
0
0
0
0
initial acceleration: 0
0
0
0
0
0
0
target position: 0.4805
-0.229
 0.389
     0
    -0
     0
  1.75
target velocity: 0
0
0
0
0
0
0
tf: 4298.34
v_max_tfs: 71.8799
518.105
22.0886
1179.93
14.8289
30.5753
4298.34
a_max_tfs:  8.5064
22.8376
4.71548
30.1382
3.37865
4.85148
84.8339
j_max_tfs:  1.55498
 3.00373
 1.04933
 3.61387
0.840214
 1.06941
 7.20455
a: -1.99876e-19
-1.44069e-18
 6.14216e-20
-4.04976e-12
-6.29602e-12
-4.05035e-12
-6.29601e-12
b:  2.14785e-15
 1.54815e-14
-6.60028e-16
 3.48145e-08
  5.4125e-08
 3.48196e-08
 5.41248e-08
c: -6.15479e-12
-4.43632e-11
 1.89135e-12
-7.48225e-05
-0.000116324
-7.48333e-05
-0.000116324
d: 0
0
0
0
0
0
0
e: 0
0
0
0
0
0
0
f:   0.529378
  0.123311
   0.37398
   2.35987
-0.0296578
 0.0611505
 -0.643318
Traceback (most recent call last):
  File "examples/home.py", line 17, in <module>
    robot.move(camera, LinearMotion(home, 1.75))
ValueError: libfranka: Attempt to set invalid transformation in motion generator. Has to be column major!
```

To reproduce:

```
git clone https://github.com/dti-research/frankx.git
cd frankx
docker build -t pantor/frankx -f docker/Dockerfile .
docker run -it --rm --network=host --privileged -v $(pwd):/code/frankx -w /code/frankx pantor/frankx
```

And inside the container build the repo:

```
mkdir build && cd build
cmake ..
make -j$(nproc)
make install
```

And finally run the example:

```
python3 example/home.py
```

**Comment by pantor** [comment]
Does this error remain if you call `robot.set_default_behavior()` in `home.py` after initiliazing the robot?

```py
# Connect to the robot
robot = Robot('172.16.0.2')
robot.set_default_behavior()
robot.recover_from_errors()
robot.set_dynamic_rel(0.1)
```

**Comment by nily-dti** [comment]
Yep. And it's the same for the cpp example.

**Comment by nily-dti** [comment]
Same error after merging your latest changes into our fork.

**Comment by pantor** [comment]
Unfortunately, the error does not occur on my setup with your Docker file. However, I've changed the libfranka version to 0.7.1, as I'm still on the controller system version 3.0. Maybe this is because of the changes regarding setting the transformations `F_T_NE` and `NE_T_EE`?

**Comment by nily-dti** [comment]
Ah... It might be. Would you know where the changes are needed to be made in order to make it work in the newest version?

**Comment by dkuss-tudresden** [comment]
First of all: awesome framework, I really appreciate your work - thank you! I would be interested in such a solution too since I have to work with libfranka 0.8.0 and the new system 4.

My experience using the libfranka 0.8.0 and frankx 0.0.3 (without Reflexxes) running C++ code:
- setDefaultBehavior can not be used due to "SetEE"
- LinearMotion runs with inverted Z-axis value (positive values move the robot to the bottom and the Z-axis value of the pose affine is decreasing)
- LinearMotion leads often to an unexpected and wrong spinning movement of the end effector and self-collision; the reason is  unknown, happened more often while the robot is running frequently, robot's break re-opening, user stop toggling or restart of the program does not help; reducing DynamicRel values to a minimum just helps temporary

**Comment by nily-dti** [comment]
@dkuss-tudresden see https://github.com/frankaemika/libfranka/issues/85#issuecomment-737235747 maybe that helps? I haven't looked further into this issue though as we managed to make @pantor 's frankr work. We've taken the frankr out of the pick-and-place package and made a standalone package that might be useful for others as well. See: [frankr](https://github.com/dti-research/frankr/tree/master) (complete with Docker image as well). We'll post a few python examples in the coming days.

**Comment by nily-dti** [comment]
And btw Franka Emika told us at DTI that we cannot downgrade the robot firmware...

**Comment by nily-dti** [comment]
@dkuss-tudresden some examples are live at [frankr](https://github.com/dti-research/frankr/tree/master).

**Comment by nily-dti** [comment]
I've finally taken the time to investigate this further with Franka Emika. It seems to be an error deep inside libfranka. See: https://github.com/frankaemika/libfranka/issues/85#issuecomment-741723277

We got permission to downgrade our controller from 4.0.4 to 3.2.1 which has removed this issue.
